# Generated by Django 2.1.3 on 2018-11-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContestApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='id',
        ),
        migrations.RemoveField(
            model_name='college',
            name='id',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='id',
        ),
        migrations.AlterField(
            model_name='challenge',
            name='challenge_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='college',
            name='college_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contest',
            name='contest_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contest',
            name='hacker_id',
            field=models.IntegerField(),
        ),
    ]
