# Generated by Django 2.1.3 on 2018-11-22 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ContestApp', '0003_auto_20181123_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('challenge_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('college_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('contest_id', models.IntegerField(primary_key=True, serialize=False)),
                ('hacker_id', models.IntegerField()),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Submission_Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_submission', models.IntegerField(max_length=10)),
                ('total_accepted_submissions', models.IntegerField(max_length=10)),
                ('Challenge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ContestApp.Challenge')),
            ],
        ),
        migrations.CreateModel(
            name='View_Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_view', models.IntegerField(max_length=10)),
                ('total_unique_view', models.IntegerField(max_length=10)),
                ('Challenge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ContestApp.Challenge')),
            ],
        ),
        migrations.AddField(
            model_name='college',
            name='contest_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ContestApp.Contest'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='college_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ContestApp.College'),
        ),
    ]
